name: AA_Nuclear
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn=1.7.1
  - scikit-image
  - matplotlib
  - scipy
  - tensorflow
  - keras
  - jupyter
  - pip
